#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 25 09:29:19 2018

@author: bart
"""

import pickle
import visuals

Experiment = 43


with open('AlleleDictionaryComplete.pickle','rb') as handle: AlleleDictionaryComplete = pickle.load(handle)

n = 3
t = 3

NeutralAlleleStrengths = visuals.PopulationVisuals.ShowAlleleStrengthComposition(AlleleDictionaryComplete, Experiment)
